all : ejercicio2lineal.out ejercicio2DyV.out

ejercicio2lineal.out : ejercicio2lineal.cpp
	g++  ejercicio2lineal.cpp -o ejercicio2lineal.out

ejercicio2DyV.out : ejercicio2DyV.cpp
	g++  ejercicio2DyV.cpp -o ejercicio2DyV.out

ejecutarlineal : scriptlineal.sh
	./scriptlineal.sh